version: '3'
services:
  nginx:
    build: ./nginx
    links:
      - node
      - public
    ports:
      - "80:80"
      - "443:443"
  node:
    build: ./node
    volumes:
      - ./node:/app
      - ./public:/public
    links:
      - mongo
    ports:
      - "8080:8080"
  public:
    build: ./public
    volumes:
      - ./public:/app
    ports:
      - "8081:8081"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  backup:
    image: yingray/mongodump
    volumes:
      - ~/Dropbox/database:/backup
    links:
      - mongo
    environment:
      - CRON_SCHEDULE=1 1 * * 2
      - BACKUP_EXPIRE_DAYS=30
      - MONGO_PORT_27017_TCP_ADDR=mongo
      - MONGO_PORT_27017_TCP_PORT=27017
